info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    foo: /foo/**
    bar: /bar/**
    zuulserver: /self/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
