eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    enabled: true
    registerWithEureka: true

ribbon:
  eureka:
    enabled: true

security:
  basic:
    enabled: false

management:
  security:
    enabled: false